### ISSUE TITLE
Packaging an app

### ISSUE THREAD

**Issue by anowell** [koute/cargo-web#1]
I'd love to see a command or arg that allowed building the app into a deployable package. Today I use [this build script](https://github.com/anowell/quasar/blob/master/www/bin/build). Something like `cargo-web package` or maybe just `cargo-web build -d <outdir> --release`.

**Comment by koute** [comment]
Definitely! I also think this is where we could put stuff like minification, amalgamation of third party libraries, SASS to CSS preprocessing, etc. But what would a deployable package be, I wonder? It seems to me that it would definitely make sense to support a "copy everything into a directory I give you" mode and maybe a "pack everything into a `.tgz` so that I can copy it over easily".

As far as naming goes I kinda like `cargo-web deploy` as, unlike `cargo-web package`, it doesn't suggest that a package (as in - a `.tgz` or something) is going to be built and it doesn't require fiddling around with extra arguments.

Should be simple enough to support the initial "copy into a directory" use case; the only other issue is - to which directory we deploy by default? From every possibility I can think of I like `./target/static` the most - it's in `target`, so it will be in people's `.gitignore` already, and the name `static` is consistent with the `static` we might have in the root of the crate, suggesting a close correlation between the two.

**Comment by anowell** [comment]
I can definitely see how this fits into a bigger pre-processing pipeline. I look forward to it.

1) `cargo-web deploy` first sounded like the kind of command that will deploy an app to GH Pages or S3 or somewhere of my choosing, but your concern about `cargo-web package` is also valid. Perhaps "deploy to a path" and "deploy to a remote location" are conceptually similar enough.

2) yeah, i chose `target/static` to fit into the scheme you already had started. I do wonder if `target/asmjs-unknown-emscripten/release/static` would be better. It's certainly not as pretty, but it works for debug vs release artifacts and asmjs vs wasm once you start supporting that. Of course, it still remains to be seen how you distinguishing building asm.js vs wasm. :-)

**Comment by Pauan** [comment]
I'm trying to write a Chrome extension using cargo-web + stdweb, and right now I have to run `cargo web build` and then manually copy-paste the generated `.js` + `.wasm` files into another folder.

So it would definitely help me out if cargo-web could handle all of that for me with a single command. I'm willing to send a pull request implementing this, though I might need some pointers if I run into any trouble.

P.S. My suggestion would be to use the name `cargo web bundle` or `cargo web release`, but I'm not too attached to any particular name.

**Comment by koute** [comment]
I've just pushed an initial version of the `cargo web deploy` subcommand to the `master`. Right now it has a preset output path (`$crate_root/target/deploy`) and I haven't yet fully tested it out yet, but you can check it out if you want.

**Comment by koute** [comment]
Just published a new version which has an initial version of this added, so closing!
