### ISSUE TITLE
cargo-web fails to build with reqwest 0.8 and openssl 1.1.1

### ISSUE THREAD

**Issue by technetos** [koute/cargo-web#139]
The problem is fixed in reqwest's master branch but not in a release yet.  

Related to: https://github.com/seanmonstar/reqwest/issues/345

```
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/tmp/cargo-installg0SfjE/release/build/openssl-d41cfa5104acbee0/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by koute** [comment]
Thanks for the heads-up! I'll update as soon as possible once new `reqwest` is released.

**Comment by dns2utf8** [comment]
This just hit me with Arch Linux.

**Comment by technetos** [comment]
$ cargo b --release                                                                                                                                                         master
    Updating git repository `https://github.com/seanmonstar/reqwest`
    Updating crates.io index
error: failed to select a version for `schannel`.
    ... required by package `native-tls v0.2.0`
    ... which is depended on by `hyper-tls v0.3.0`
    ... which is depended on by `reqwest v0.9.0-pre (https://github.com/seanmonstar/reqwest#68d012e9)`
    ... which is depended on by `cargo-web v0.6.16 (/usr/dataplus/cargo-web)`
versions that meet the requirements `^0.1.13` are: 0.1.13

```all possible versions conflict with previously selected packages.

  previously selected package `schannel v0.1.12`
    ... which is depended on by `native-tls v0.1.5`
    ... which is depended on by `tokio-tls v0.1.4`
    ... which is depended on by `websocket v0.20.2`
    ... which is depended on by `cargo-web v0.6.16 (/usr/dataplus/cargo-web)`

failed to select a version for `schannel` which could resolve this conflict

**Comment by dns2utf8** [comment]
I managed to build it inside a docker container
```bash
docker run --rm -it --user "$(id -u)":"$(id -g)" -v "$PWD":/usr/src/myapp -w /usr/src/myapp rust:1.29.0 /bin/bash
cargo install cargo-web
cp /usr/local/cargo/bin/cargo-web .
```

**Comment by koute** [comment]
You can also always grab the precompiled binary:

```rust
CARGO_WEB_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/koute/cargo-web/releases/latest)
CARGO_WEB_VERSION=$(echo $CARGO_WEB_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
CARGO_WEB_URL="https://github.com/koute/cargo-web/releases/download/$CARGO_WEB_VERSION/cargo-web-x86_64-unknown-linux-gnu.gz"

echo "Downloading cargo-web from: $CARGO_WEB_URL"
curl -L $CARGO_WEB_URL | gzip -d > cargo-web
chmod +x cargo-web

mkdir -p ~/.cargo/bin
mv cargo-web ~/.cargo/bin
```

**Comment by koute** [comment]
It looks like updating to the newest `reqwest` still won't make it compile (due to other dependencies as noted by @technetos).

For now I've simply turned on `openssl-sys` vendoring, which seems to fix the issue on my fully updated Arch system.

**Comment by bernardobelchior** [comment]
I'm having the same problem.

> For now I've simply turned on `openssl-sys` vendoring, which seems to fix the issue on my fully updated Arch system.
Could you explain how to achieve this?

**Comment by koute** [comment]
@bernardobelchior You mean in general, or in context of `cargo-web`? `cargo-web`'s `master` has already this applied.

**Comment by jagu-sayan** [comment]
I fix this issue on Archlinux [like this](https://github.com/SpaceManiac/discord-rs/issues/113#issuecomment-304465625):
```bash
pacman -S openssl
OPENSSL_INCLUDE_DIR=/usr/include/openssl-1.0 OPENSSL_LIB_DIR=/usr/lib/openssl-1.0 cargo install cargo-web
```

**Comment by technetos** [comment]
@jagu-sayan cargo-web should work ootb now.

**Comment by jagu-sayan** [comment]
@technetos Sadly, I still have the issue, certainly due to another dependency :/
<details>
<pre>
   Compiling serde_json v1.0.32                                                                                                                                                                                     
error: failed to run custom build command for `openssl v0.9.24`                                                                                                                                                     
process didn't exit successfully: `/tmp/cargo-install6DpnMF/release/build/openssl-f9ad91213ceefec1/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/jagu/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-web v0.6.16`, intermediate artifacts can be found at `/tmp/cargo-install6DpnMF`
</pre>
</details>
