### ISSUE TITLE
Running `cargo web test` multiple times without modifying code leads to a panic

### ISSUE THREAD

**Issue by slimsag** [koute/cargo-web#21]
I just started with `cargo web` and I noticed that if I run commands multiple times (e.g. `cargo web test`) that because artifacts in `target/` have not changed `cargo-web` panics:

```
$ cargo web test --nodejs --target-webasm
warning: debug builds on the wasm-unknown-unknown are currently totally broken
         forcing a release build
    Finished release [optimized] target(s) in 0.0 secs
thread 'main' panicked at 'internal error: nothing changed so I don't know which artifact corresponds to this build', /Users/stephen/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-web-0.4.0/src/main.rs:830:16
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Working around this issue is easy enough, as it turns out: I just needed to modify my code in some way before running the command again. But the error message here was not obvious to me initially, and so it had me searching online for solutions without finding anything.

**Comment by koute** [comment]
Yeah, unfortunately this is a known bug, and is mostly there because there is currently no sane way of getting the name of the artifacts out of cargo, so what I'm doing right now is this:

1. See what files are in the artifacts directory.
2. Build.
3. See what files changed or were created, and treat those as build artifacts.

If the build is a no-op then obviously nothing changes, so I can't use this method to figure out what are the artifacts of what the user tried to build or run.

See issues https://github.com/rust-lang/cargo/issues/3855 and https://github.com/rust-lang/cargo/issues/1924 for more details.

I've modified the panic message to be a tad bit more descriptive.

**Comment by koute** [comment]
Fixed on `master`.
