### ISSUE TITLE
Configurable output directory

### ISSUE THREAD

**Issue by karuna** [koute/cargo-web#64]
Hey @koute , is it possible to make `cargo web deploy` to output to `target-dir` ?
https://doc.rust-lang.org/cargo/reference/config.html

I've configured cargo `target-dir` but it always output to current cargo dir. Or is it possible to specify output dir like `cargo web deploy --output /some/dir` ?

**Comment by koute** [comment]
It's currently not possible to do that, although if you need it you have two options:

1) You can add it to `cargo-web` yourself. (: It should be simple enough to do - just add a `-d <directory>`/`--output-dir <directory>` argument and then in `cmd_deploy.rs` output the artifacts there instead of to `target/deploy`.
2) You can symlink the `target/deploy` to a directory of your choice and *I think* it should work? (I haven't tested it out though.)

**Comment by karuna** [comment]
I will look into that. Thank you.
