### ISSUE TITLE
How about change default target  to wasm32-unknown-unknown

### ISSUE THREAD

**Issue by anykao** [koute/cargo-web#89]
I wonder what make more sense between `asmjs-unknown-emscripten` and `wasm32-unknown-unknown`. 
Show your opinion by clicking the reaction.

**Comment by Pauan** [comment]
But there's three targets: `asmjs-unknown-emscripten`, `wasm32-unknown-emscripten`, and `wasm32-unknown-unknown`, so the reactions aren't good enough for voting.

Personally, my vote goes for `wasm32-unknown-unknown`, since it's the lightest-weight, and you usually only need the other targets when you're porting existing Rust projects to wasm (as opposed to building a new wasm project from scratch).

**Comment by anykao** [comment]
I agree with you.  The default target should reflect the ordinary usage. 

Then the vote may be
=================
* change default target to `wasm32-unknown-unknown` 👍
* no change, it doesn't  deserve the hassle  👎

**Comment by koute** [comment]
I agree that `wasm32-unknown-unknown` should be the default *eventually*, however I feel like it's still too early for that. (`println!` doesn't work on `wasm32-unknown-unknown`, there are still semi-breaking changes from time-to-time, etc.)

Personally I'd like to have at least three things before switching to `wasm32-unknown-unknown` by default:
1) a working `println!` (e.g. not only the users expect that it should work, but it's necessary for running the tests, otherwise you get no output)
2) stable procedural macros and a stable way to generate custom sections from code (so that I can rewrite the `js!` macro to not be so super hacky)
3) the Rust team officially advertises the `wasm32-unknown-unknown` to be usable (in any form) on stable Rust

**Comment by anykao** [comment]
Thanks for your consideration.
I just hope that if there are enough requests to use `wasm32-unknown-unknown ` by default, there should be a convenient solution.

**Comment by lucab** [comment]
This project README specifies that a nightly toolchain is required to target `wasm32-unknown-unknown`. Is that still the case?

**Comment by Timmmm** [comment]
> Maybe it's possible for cargo-web to honor this setting?

I made #128 to track this.
